// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductsResponse products response
//
// swagger:model ProductsResponse
type ProductsResponse struct {

	// Description for product
	// Example: Awesome coffee for your new day.
	Description string `json:"description,omitempty"`

	// ID of product in system
	// Example: 123
	ID int64 `json:"id,omitempty"`

	// Name of product
	// Example: Cappuccino coffee
	Name string `json:"name,omitempty"`

	// Price of product in dollar
	// Example: 12
	Price float64 `json:"price,omitempty"`

	// SKU of product
	// following format: xxx-xxx-xxx
	// Example: 123-123-123
	SKU string `json:"sku,omitempty"`
}

// Validate validates this products response
func (m *ProductsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this products response based on context it is used
func (m *ProductsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductsResponse) UnmarshalBinary(b []byte) error {
	var res ProductsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
