// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/codewithhoa/building-microservice-with-go/product-api/pkg/sdk/models"
)

// ListProductsReader is a Reader for the ListProducts structure.
type ListProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListProductsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListProductsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListProductsOK creates a ListProductsOK with default headers values
func NewListProductsOK() *ListProductsOK {
	return &ListProductsOK{}
}

/*
ListProductsOK describes a response with status code 200, with default header values.

successful operation
*/
type ListProductsOK struct {
	Payload *models.SuccessListProductsResponses
}

// IsSuccess returns true when this list products o k response has a 2xx status code
func (o *ListProductsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list products o k response has a 3xx status code
func (o *ListProductsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list products o k response has a 4xx status code
func (o *ListProductsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list products o k response has a 5xx status code
func (o *ListProductsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list products o k response a status code equal to that given
func (o *ListProductsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list products o k response
func (o *ListProductsOK) Code() int {
	return 200
}

func (o *ListProductsOK) Error() string {
	return fmt.Sprintf("[GET /products][%d] listProductsOK  %+v", 200, o.Payload)
}

func (o *ListProductsOK) String() string {
	return fmt.Sprintf("[GET /products][%d] listProductsOK  %+v", 200, o.Payload)
}

func (o *ListProductsOK) GetPayload() *models.SuccessListProductsResponses {
	return o.Payload
}

func (o *ListProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessListProductsResponses)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProductsInternalServerError creates a ListProductsInternalServerError with default headers values
func NewListProductsInternalServerError() *ListProductsInternalServerError {
	return &ListProductsInternalServerError{}
}

/*
ListProductsInternalServerError describes a response with status code 500, with default header values.

internal error occur in server
*/
type ListProductsInternalServerError struct {
	Payload *models.ErrorResponses
}

// IsSuccess returns true when this list products internal server error response has a 2xx status code
func (o *ListProductsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list products internal server error response has a 3xx status code
func (o *ListProductsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list products internal server error response has a 4xx status code
func (o *ListProductsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list products internal server error response has a 5xx status code
func (o *ListProductsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list products internal server error response a status code equal to that given
func (o *ListProductsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list products internal server error response
func (o *ListProductsInternalServerError) Code() int {
	return 500
}

func (o *ListProductsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /products][%d] listProductsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListProductsInternalServerError) String() string {
	return fmt.Sprintf("[GET /products][%d] listProductsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListProductsInternalServerError) GetPayload() *models.ErrorResponses {
	return o.Payload
}

func (o *ListProductsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponses)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProductsDefault creates a ListProductsDefault with default headers values
func NewListProductsDefault(code int) *ListProductsDefault {
	return &ListProductsDefault{
		_statusCode: code,
	}
}

/*
ListProductsDefault describes a response with status code -1, with default header values.

successful operation
*/
type ListProductsDefault struct {
	_statusCode int

	Payload *models.SuccessListProductsResponses
}

// IsSuccess returns true when this list products default response has a 2xx status code
func (o *ListProductsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list products default response has a 3xx status code
func (o *ListProductsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list products default response has a 4xx status code
func (o *ListProductsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list products default response has a 5xx status code
func (o *ListProductsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list products default response a status code equal to that given
func (o *ListProductsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list products default response
func (o *ListProductsDefault) Code() int {
	return o._statusCode
}

func (o *ListProductsDefault) Error() string {
	return fmt.Sprintf("[GET /products][%d] listProducts default  %+v", o._statusCode, o.Payload)
}

func (o *ListProductsDefault) String() string {
	return fmt.Sprintf("[GET /products][%d] listProducts default  %+v", o._statusCode, o.Payload)
}

func (o *ListProductsDefault) GetPayload() *models.SuccessListProductsResponses {
	return o.Payload
}

func (o *ListProductsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessListProductsResponses)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
