// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/codewithhoa/building-microservice-with-go/product-api/pkg/sdk/models"
)

// PostProductReader is a Reader for the PostProduct structure.
type PostProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostProductCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostProductBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostProductInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPostProductDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostProductCreated creates a PostProductCreated with default headers values
func NewPostProductCreated() *PostProductCreated {
	return &PostProductCreated{}
}

/*
PostProductCreated describes a response with status code 201, with default header values.

successful operation and no data to return.
*/
type PostProductCreated struct {
}

// IsSuccess returns true when this post product created response has a 2xx status code
func (o *PostProductCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post product created response has a 3xx status code
func (o *PostProductCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post product created response has a 4xx status code
func (o *PostProductCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post product created response has a 5xx status code
func (o *PostProductCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post product created response a status code equal to that given
func (o *PostProductCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post product created response
func (o *PostProductCreated) Code() int {
	return 201
}

func (o *PostProductCreated) Error() string {
	return fmt.Sprintf("[POST /products][%d] postProductCreated ", 201)
}

func (o *PostProductCreated) String() string {
	return fmt.Sprintf("[POST /products][%d] postProductCreated ", 201)
}

func (o *PostProductCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostProductBadRequest creates a PostProductBadRequest with default headers values
func NewPostProductBadRequest() *PostProductBadRequest {
	return &PostProductBadRequest{}
}

/*
PostProductBadRequest describes a response with status code 400, with default header values.

internal error occur in server
*/
type PostProductBadRequest struct {
	Payload *models.ErrorResponses
}

// IsSuccess returns true when this post product bad request response has a 2xx status code
func (o *PostProductBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post product bad request response has a 3xx status code
func (o *PostProductBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post product bad request response has a 4xx status code
func (o *PostProductBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post product bad request response has a 5xx status code
func (o *PostProductBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post product bad request response a status code equal to that given
func (o *PostProductBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post product bad request response
func (o *PostProductBadRequest) Code() int {
	return 400
}

func (o *PostProductBadRequest) Error() string {
	return fmt.Sprintf("[POST /products][%d] postProductBadRequest  %+v", 400, o.Payload)
}

func (o *PostProductBadRequest) String() string {
	return fmt.Sprintf("[POST /products][%d] postProductBadRequest  %+v", 400, o.Payload)
}

func (o *PostProductBadRequest) GetPayload() *models.ErrorResponses {
	return o.Payload
}

func (o *PostProductBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponses)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostProductInternalServerError creates a PostProductInternalServerError with default headers values
func NewPostProductInternalServerError() *PostProductInternalServerError {
	return &PostProductInternalServerError{}
}

/*
PostProductInternalServerError describes a response with status code 500, with default header values.

internal error occur in server
*/
type PostProductInternalServerError struct {
	Payload *models.ErrorResponses
}

// IsSuccess returns true when this post product internal server error response has a 2xx status code
func (o *PostProductInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post product internal server error response has a 3xx status code
func (o *PostProductInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post product internal server error response has a 4xx status code
func (o *PostProductInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post product internal server error response has a 5xx status code
func (o *PostProductInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post product internal server error response a status code equal to that given
func (o *PostProductInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post product internal server error response
func (o *PostProductInternalServerError) Code() int {
	return 500
}

func (o *PostProductInternalServerError) Error() string {
	return fmt.Sprintf("[POST /products][%d] postProductInternalServerError  %+v", 500, o.Payload)
}

func (o *PostProductInternalServerError) String() string {
	return fmt.Sprintf("[POST /products][%d] postProductInternalServerError  %+v", 500, o.Payload)
}

func (o *PostProductInternalServerError) GetPayload() *models.ErrorResponses {
	return o.Payload
}

func (o *PostProductInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponses)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostProductDefault creates a PostProductDefault with default headers values
func NewPostProductDefault(code int) *PostProductDefault {
	return &PostProductDefault{
		_statusCode: code,
	}
}

/*
PostProductDefault describes a response with status code -1, with default header values.

successful operation and no data to return.
*/
type PostProductDefault struct {
	_statusCode int
}

// IsSuccess returns true when this post product default response has a 2xx status code
func (o *PostProductDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post product default response has a 3xx status code
func (o *PostProductDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post product default response has a 4xx status code
func (o *PostProductDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post product default response has a 5xx status code
func (o *PostProductDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post product default response a status code equal to that given
func (o *PostProductDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the post product default response
func (o *PostProductDefault) Code() int {
	return o._statusCode
}

func (o *PostProductDefault) Error() string {
	return fmt.Sprintf("[POST /products][%d] postProduct default ", o._statusCode)
}

func (o *PostProductDefault) String() string {
	return fmt.Sprintf("[POST /products][%d] postProduct default ", o._statusCode)
}

func (o *PostProductDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
