// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/codewithhoa/building-microservice-with-go/product-api/pkg/sdk/models"
)

// NewPutProductParams creates a new PutProductParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProductParams() *PutProductParams {
	return &PutProductParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutProductParamsWithTimeout creates a new PutProductParams object
// with the ability to set a timeout on a request.
func NewPutProductParamsWithTimeout(timeout time.Duration) *PutProductParams {
	return &PutProductParams{
		timeout: timeout,
	}
}

// NewPutProductParamsWithContext creates a new PutProductParams object
// with the ability to set a context for a request.
func NewPutProductParamsWithContext(ctx context.Context) *PutProductParams {
	return &PutProductParams{
		Context: ctx,
	}
}

// NewPutProductParamsWithHTTPClient creates a new PutProductParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProductParamsWithHTTPClient(client *http.Client) *PutProductParams {
	return &PutProductParams{
		HTTPClient: client,
	}
}

/*
PutProductParams contains all the parameters to send to the API endpoint

	for the put product operation.

	Typically these are written to a http.Request.
*/
type PutProductParams struct {

	/* Body.

	   Product object that needs to be added to the database
	*/
	Body *models.ProductParams

	/* ID.

	   The id of the product that you want to do somethings on it.

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductParams) WithDefaults() *PutProductParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put product params
func (o *PutProductParams) WithTimeout(timeout time.Duration) *PutProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put product params
func (o *PutProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put product params
func (o *PutProductParams) WithContext(ctx context.Context) *PutProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put product params
func (o *PutProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put product params
func (o *PutProductParams) WithHTTPClient(client *http.Client) *PutProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put product params
func (o *PutProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put product params
func (o *PutProductParams) WithBody(body *models.ProductParams) *PutProductParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put product params
func (o *PutProductParams) SetBody(body *models.ProductParams) {
	o.Body = body
}

// WithID adds the id to the put product params
func (o *PutProductParams) WithID(id int64) *PutProductParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put product params
func (o *PutProductParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
